---
- name: Install xmr-stak
  hosts: all
  gather_facts: true

  vars:
    deploy_user_name: cyn

    epelReleaseMajorVersion: 7
    
    required_packages: 
      - cmake3
      - devtoolset-7-gcc
      - devtoolset-7-gcc-c++
      - hwloc-devel
      - libmicrohttpd-devel
      - openssl-devel
      - make
      - git
      - screen

  tasks:
    - name: install epel-release
      yum: 
        name: epel-release
        state: present
      become: yes
      become_user: root

    - name: install centos-release-scl
      yum: 
        name: centos-release-scl
        state: present
      become: yes
      become_user: root

    - name: run update 
      yum:
        name: '*'
        state: latest
        update_cache: yes
        exclude: placeholder*
      become: yes
      become_user: root

    - name: install required packages
      yum: 
        name: "{{ required_packages }}"
        state: present
      become: yes
      become_user: root

    - name: Create install script
      copy:
        dest: "/home/cyn/xmr-install.sh"
        content: |
          #!/bin/bash
          scl enable devtoolset-7 bash
          git clone https://github.com/fireice-uk/xmr-stak.git
          mkdir -p xmr-stak/build
          cd xmr-stak/build
          export CC=/usr/bin/gcc
          export CXX=/opt/rh/devtoolset-7/root/usr/bin/g++
          cmake3 .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
        mode: 0774
    
    - name: Execute install shell script
      shell: /home/cyn/xmr-install.sh > install.log

    - name: install 
      make: 
        chdir: /home/cyn/xmr-stak/build
        target: install
      become: yes

    - name: copy runner script
      copy:
        dest: "home/cyn/xmr-run.sh"
        content: |
          #!/bin/bash
          screen
          /home/cyn/xmr-stak/build/bin/xmr-stak -o de.minexmr.com:80 -u 43vMLm5bxw6Vwz7tMnKYaoaxmSLnGuaXXBTro7cUruddSe5R6TPCUy1QT2vDduqKUpVm5Q2fbE1MgHX925A3x39D7HXEWdp -r  -p x --currency monero7
        mode: 0774

    - name: run xmr
      shell: /home/cyn/xmr-run.sh &

