---
- name: Run yum update
  hosts: all #"{{ awx_hosts }}"
  gather_facts: true
  
  tasks:
  - name: run update on remote devices
    yum:
      name: '*'
      state: latest
      exclude: placeholder*

