---
- name: Show versions
  hosts: "{{ awx_hosts }}"
  gather_facts: true
  
  tasks:
  - name: run show version on remote devices
    bigip_command:
      commands: show sys version
      server: "{{ansible_env.SSH_CONNECTION.split(' ')[2]}}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: no
    register: result
    delegate_to: localhost
    
  - debug:
    var: result.stdout_lines
