---
- name: Sync cfg
  hosts: 10.78.200.137
  gather_facts: false
  
  tasks:
  - name: copy dir
    become: true
    copy:
      src: /var/lib/awx/projects/_6__f5_testing/save
      dest: /data/F5
      directory_mode: yes
